Repository codesquad-member-2020/sidedish-05, pull requests merged in 2020-04, with the labels that each got.

#10 [FE] [#8] CRA 환경 설정하기
  FE/sidedish/.gitignore
  FE/sidedish/README.md
  FE/sidedish/package-lock.json
  FE/sidedish/package.json
  FE/sidedish/public/favicon.ico
  FE/sidedish/public/index.html
  FE/sidedish/public/logo192.png
  FE/sidedish/public/logo512.png
  FE/sidedish/public/manifest.json
  FE/sidedish/public/robots.txt
  FE/sidedish/src/App.js
  FE/sidedish/src/App.test.js
  FE/sidedish/src/index.js
  FE/sidedish/src/serviceWorker.js
  FE/sidedish/src/setupTests.js
Labels: FE, Feature

#30 [iOS] #24 Toaster 패키지 설치
  iOS/SideDish/Podfile
  iOS/SideDish/Podfile.lock
  iOS/SideDish/Pods/Headers/Private/Toaster/Toaster.h
  iOS/SideDish/Pods/Headers/Public/Toaster/Toaster-umbrella.h
  iOS/SideDish/Pods/Headers/Public/Toaster/Toaster.h
  iOS/SideDish/Pods/Headers/Public/Toaster/Toaster.modulemap
  iOS/SideDish/Pods/Manifest.lock
  iOS/SideDish/Pods/Pods.xcodeproj/project.pbxproj
  iOS/SideDish/Pods/Pods.xcodeproj/xcuserdata/jinie.xcuserdatad/xcschemes/Pods-SideDish.xcscheme
  iOS/SideDish/Pods/Pods.xcodeproj/xcuserdata/jinie.xcuserdatad/xcschemes/Toaster.xcscheme
  iOS/SideDish/Pods/Pods.xcodeproj/xcuserdata/jinie.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/SideDish/Pods/Target Support Files/Pods-SideDish/Pods-SideDish-acknowledgements.markdown
  iOS/SideDish/Pods/Target Support Files/Pods-SideDish/Pods-SideDish-acknowledgements.plist
  iOS/SideDish/Pods/Target Support Files/Pods-SideDish/Pods-SideDish-dummy.m
  iOS/SideDish/Pods/Target Support Files/Pods-SideDish/Pods-SideDish-umbrella.h
  iOS/SideDish/Pods/Target Support Files/Pods-SideDish/Pods-SideDish.debug.xcconfig
  iOS/SideDish/Pods/Target Support Files/Pods-SideDish/Pods-SideDish.modulemap
  iOS/SideDish/Pods/Target Support Files/Pods-SideDish/Pods-SideDish.release.xcconfig
  iOS/SideDish/Pods/Target Support Files/Toaster/Toaster-dummy.m
  iOS/SideDish/Pods/Target Support Files/Toaster/Toaster-prefix.pch
  iOS/SideDish/Pods/Target Support Files/Toaster/Toaster-umbrella.h
  iOS/SideDish/Pods/Target Support Files/Toaster/Toaster.debug.xcconfig
  iOS/SideDish/Pods/Target Support Files/Toaster/Toaster.modulemap
  iOS/SideDish/Pods/Target Support Files/Toaster/Toaster.release.xcconfig
  iOS/SideDish/Pods/Toaster/LICENSE
  iOS/SideDish/Pods/Toaster/README.md
  iOS/SideDish/Pods/Toaster/Sources/Toast.swift
  iOS/SideDish/Pods/Toaster/Sources/ToastCenter.swift
  iOS/SideDish/Pods/Toaster/Sources/ToastView.swift
  iOS/SideDish/Pods/Toaster/Sources/ToastWindow.swift
  iOS/SideDish/Pods/Toaster/Sources/Toaster.h
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/SideDish/SideDish.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/SideDish/SideDish.xcodeproj/project.xcworkspace/xcuserdata/jinie.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/SideDish/SideDish.xcodeproj/xcuserdata/jinie.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/SideDish/SideDish.xcworkspace/contents.xcworkspacedata
  iOS/SideDish/SideDish.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/SideDish/SideDish.xcworkspace/xcuserdata/jinie.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/SideDish/SideDish/AppDelegate.swift
  iOS/SideDish/SideDish/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/Contents.json
  iOS/SideDish/SideDish/Base.lproj/LaunchScreen.storyboard
  iOS/SideDish/SideDish/Base.lproj/Main.storyboard
  iOS/SideDish/SideDish/Info.plist
  iOS/SideDish/SideDish/SceneDelegate.swift
  iOS/SideDish/SideDish/ViewController.swift
Labels: iOS

#32 [FE] Emotion, React Slick, axios 환경 설정하기
  FE/sidedish/.gitignore
  FE/sidedish/package-lock.json
  FE/sidedish/package.json
  FE/sidedish/yarn.lock
Labels: FE

#37 [FE] 카테고리(Navigation Bar) 기능
  FE/sidedish/public/favicon.ico
  FE/sidedish/public/index.html
  FE/sidedish/public/logo192.png
  FE/sidedish/public/logo512.png
  FE/sidedish/public/main-logo.png
  FE/sidedish/public/manifest.json
  FE/sidedish/src/App.js
  FE/sidedish/src/Reset.jsx
  FE/sidedish/src/components/Category/Category.jsx
  FE/sidedish/src/components/Category/CategoryDetail.jsx
  FE/sidedish/src/components/Category/CategoryList.jsx
  FE/sidedish/src/components/Category/categoryData.js
Labels: FE, Feature

#39 [#3] fix: SubList에 key값 index로 부여하게 수정
  FE/sidedish/src/components/Category/CategoryDetail.jsx
Labels: FE, enhancement

#44 [FE] 캐러셀 슬라이드 / 상품 기능 완료
  FE/sidedish/package.json
  FE/sidedish/public/images/main-logo.png
  FE/sidedish/public/index.html
  FE/sidedish/src/App.js
  FE/sidedish/src/common/config.js
  FE/sidedish/src/components/Header/Header.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/DetailProduct.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/ImageList.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/RecommandProductList.jsx
  FE/sidedish/src/components/ProductCarousel/Product.jsx
  FE/sidedish/src/components/ProductCarousel/Product/Product.jsx
  FE/sidedish/src/components/ProductCarousel/Product/ProductBadge.jsx
  FE/sidedish/src/components/ProductCarousel/Product/ProductImage.jsx
  FE/sidedish/src/components/ProductCarousel/Product/ProductInfo.jsx
  FE/sidedish/src/components/ProductCarousel/ProductCarousel.jsx
  FE/sidedish/src/components/ProductCarousel/ProductCarouselTitle.jsx
  FE/sidedish/src/components/ProductCarousel/ProductCatousel.jsx
  FE/sidedish/src/components/ProductCarousel/navigate_before.png
  FE/sidedish/src/components/ProductCarousel/navigate_next.png
  FE/sidedish/src/lib/fetchData.js
  FE/sidedish/src/lib/usePromise.js
  FE/sidedish/yarn.lock
Labels: FE, Feature

#46 [FE] 반찬 전체보기 기능
  FE/sidedish/src/App.js
  FE/sidedish/src/components/ProductCarousel/MoreCarousel.jsx
  FE/sidedish/src/components/ProductCarousel/Product/ProductImage.jsx
Labels: FE, Feature

#49 [FE] 반찬 전체보기 클릭했을 때 버튼 사라지게 하는 기능
  FE/sidedish/src/components/ProductCarousel/MoreCarousel.jsx
Labels: FE, enhancement

#45 [FE][리뷰요청] 캐러셀 슬라이드 / 상품 기능 완료
  FE/sidedish/package.json
  FE/sidedish/public/images/main-logo.png
  FE/sidedish/public/index.html
  FE/sidedish/src/App.js
  FE/sidedish/src/common/config.js
  FE/sidedish/src/components/Header/Header.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/DetailProduct.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/ImageList.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/RecommandProductList.jsx
  FE/sidedish/src/components/ProductCarousel/Product.jsx
  FE/sidedish/src/components/ProductCarousel/Product/Product.jsx
  FE/sidedish/src/components/ProductCarousel/Product/ProductBadge.jsx
  FE/sidedish/src/components/ProductCarousel/Product/ProductImage.jsx
  FE/sidedish/src/components/ProductCarousel/Product/ProductInfo.jsx
  FE/sidedish/src/components/ProductCarousel/ProductCarousel.jsx
  FE/sidedish/src/components/ProductCarousel/ProductCarouselTitle.jsx
  FE/sidedish/src/components/ProductCarousel/ProductCatousel.jsx
  FE/sidedish/src/components/ProductCarousel/navigate_before.png
  FE/sidedish/src/components/ProductCarousel/navigate_next.png
  FE/sidedish/src/lib/fetchData.js
  FE/sidedish/src/lib/usePromise.js
  FE/sidedish/yarn.lock
Labels: FE, Feature, fe리뷰요청

#51 [FE] 상세페이지 기능 일부 완료
  FE/sidedish/src/common/config.js
  FE/sidedish/src/components/ProductCarousel/DetailProduct/DetailProduct.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/ImageList.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/Modal.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/ProductInfo.jsx
  FE/sidedish/src/components/ProductCarousel/Product/Product.jsx
  FE/sidedish/src/components/ProductCarousel/Product/ProductImage.jsx
Labels: FE, Feature

#52 [FE] 캐러셀 슬라이드 영역 리팩토링
  FE/sidedish/src/components/ProductCarousel/Product/Product.jsx
  FE/sidedish/src/components/ProductCarousel/Product/ProductImage.jsx
Labels: FE, enhancement

#56 [FE] 헤더 영역 완료
  FE/sidedish/src/App.js
  FE/sidedish/src/App.test.js
  FE/sidedish/src/components/Category/CategoryList.jsx
  FE/sidedish/src/components/Header/Header.jsx
  FE/sidedish/src/components/Header/HeaderMainContent.jsx
  FE/sidedish/src/components/Header/LocalNaviBar.jsx
  FE/sidedish/src/components/Header/headerData.js
  FE/sidedish/src/components/Header/main-logo.png
  FE/sidedish/src/components/Header/search.png
  FE/sidedish/src/setupTests.js
Labels: FE, Feature

#57 [BE] 요청한 데이터 제공
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/controller/CategoryController.java
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/domain/Category.java
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/domain/Sidedish.java
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/dto/CategoryDto.java
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/dto/DetailDto.java
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/dto/OverviewDto.java
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/dto/ResponseDto.java
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/repository/DetailDao.java
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/repository/OverviewDao.java
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/service/ApiService.java
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/service/CategoryService.java
  BE/sidedish-5/src/main/resources/schema.sql
Labels: BE, Feature

#58 [FE] 상세 페이지 - 개수 선택, 이미지 썸네일 리스트 기능 완료
  FE/sidedish/src/components/ProductCarousel/DetailProduct/DetailProduct.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/ImageList.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/ProductInfo.jsx
  FE/sidedish/src/components/ProductCarousel/Product/Product.jsx
  FE/sidedish/src/components/ProductCarousel/Product/ProductImage.jsx
  FE/sidedish/src/components/ProductCarousel/ProductCarousel.jsx
Labels: FE, Feature

#59 [#19] github OAuth
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/controller/LoginController.java
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/domain/GithubToken.java
  BE/sidedish-5/src/main/java/com/codesquad/sidedish5/service/LoginService.java
Labels: BE, Feature

#60 [FE] OAuth 링크 추가
  FE/sidedish/src/common/config.js
  FE/sidedish/src/components/Header/LocalNaviBar.jsx
Labels: FE, Feature

#61 [FE] OAuth로 로그인/로그아웃 기능 완료
  FE/sidedish/src/components/Header/LocalNaviBar.jsx
  FE/sidedish/src/components/Header/headerData.js
Labels: FE, Feature

#62 [FE] 리팩토링
  FE/sidedish/src/Reset.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/DetailProduct.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/DetailProductInfo.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/RecommandProduct.jsx
  FE/sidedish/src/components/ProductCarousel/DetailProduct/RecommandProductList.jsx
  FE/sidedish/src/components/ProductCarousel/Product/Product.jsx
  FE/sidedish/src/components/ProductCarousel/Product/ProductImage.jsx
  FE/sidedish/src/components/ProductCarousel/ProductCarousel.jsx
  FE/sidedish/src/components/ProductCarousel/loading.svg
  FE/sidedish/src/lib/fetchData.js
  FE/sidedish/src/lib/usePromise.js
Labels: FE, enhancement
